config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'products#index'

  resources :users, only: [:show]
  resources :products, only: [:show, :new, :create] do
    resources :reviews, only: [:new, :create]
    collection do
      get 'search'
      get 'search_director'
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many  :reviews

  validates :title, :director, presence: true

  def review_average
    reviews.average(:rate).round
    # self.reviews.average(:rate).round：上記の略さず記載の形
      # 『self』を用いたのは、インスタンス変数productをそのまま記載するとエラーになる為。
      # レシーバ（メソッドを使用したインスタンス自体の事）に対して適用することが出来る。
  end
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to  :product
  belongs_to  :user

end

app/models/scraping.rb
 class Scraping
  def self.movie_urls
    links = []
    agent = Mechanize.new

    # パスの部分を変数で定義(はじめは、空にしておきます)
    next_url = ""

    while true do
      current_page = agent.get("http://review-movie.herokuapp.com/" + next_url)
      elements = current_page.search(".entry-title a")
      elements.each do |ele|
        links << ele.get_attribute('href')
      end

      # 「次へ」を表すタグを取得
      # 数字のページネイトではなく、『次へ』を指定
      next_link = current_page.at(".pagination .next a")

      # next_linkがなかったらwhile文を抜ける
      unless next_link
        break
      end

      # そのタグからhref属性の値を取得
      # next_url = next_link.get_attribute("href")と同じ内容
      next_url = next_link[:href]
    end

    links.each do |link|
      get_product('http://review-movie.herokuapp.com' + link)
    end
  end

  def self.get_product(link)
    agent = Mechanize.new
    page = agent.get(link)

    title = page.at(".entry-title").inner_text if page.at('.entry-title')
    image_url = page.at(".entry-content img")[:src] if page.at(".entry-content img")

    director = page.at(".director span").inner_text if page.at('.director span')
    detail = page.at(".entry-content p").inner_text if page.at('.entry-content p')
    # 指定箇所丸ごと取得してしまうので、『.inner_text』を付ける。
    open_date = page.at(".date span").inner_text if page.at('.date span')

    # whereの対象をtitleカラムのみに変更
    product = Product.where(title: title).first_or_initialize
    product.image_url = image_url
    product.director = director
    product.detail = detail
    product.open_date = open_date
    product.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # バリデート設定
  validates :nickname, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many  :reviews

  # has_attached_file :カラム名,
                    # styles:  { medium: "画像サイズ", thumb: "画像サイズ" }
  # サイズを指定するための属性はstyles。
  # stylesではどのような種類の画像をどの大きさで保存するか指定する。
  # 「medium」や「thumb」はImageMagickで保存できる画像の種類です。
  # 画像サイズの指定はImageMagickでの指定方法に準じる。
  has_attached_file :avatar,
                    styles:  { medium: "300x300#", thumb: "100x100#" }

  # validates_attachment_content_type :カラム名,
                                    # content_type: ["画像の種類"]
  # ["画像の種類"]には、配列で指定する。
  validates_attachment_content_type :avatar,
                                    content_type: ["image/jpg","image/jpeg","image/png"]



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # サインアップ時、保存項目追加のための設定
  # 記載はDeviseコントローラーを継承したコントローラ、もしくはApplicationController。
  # ifオプションを指定して、before_actionを呼び出す条件を指定する。
  # （今回はコントローラの種類を指定する）
  before_action :configure_permitted_parameters, if: :devise_controller?
  # 『devise_parameter_sanitizer』メソッドはDeviseのコントローラ以外で使用不可。
  # （deviseで追加されたメソッドの為）
  # すべてのコントローラがApplicationControllerを継承している為、
  # すべてのコントローラのアクションの前で『devise_parameter_sanitizer』メソッドが呼び出されてしまう。

  # 複数ページで部分テンプレートを使用時、呼び出しコントローラーによって表示内容を変える記述
  before_action :request_path
  def request_path
      @path = controller_path + '#' + action_name #『controller_name』にも値が入っている
      def @path.is(*str) #引数に『*』がある事で、その引数は配列となる。
          str.map{|s| self.include?(s)}.include?(true)
      end
  end
  # このメソッドの定義結果は『:request_path』（シンボル型）
  # 『str.map{|s| self.include?(s)}』の実行内容が『:is』。

  # サインアウト後のリダイレクト先を設定
  # 引数には『resource』を渡す（deviseのメソッドを上書きしている為）
  # 返り値にリダイレクト先のURLを指定
  def after_sign_out_path_for(resource)
    '/users/sign_in'
  end

  # サインアップ時、保存項目追加のための設定
  # 通常のストパラ同様、直接書かずに別途書く。
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar])
  # devise_parameter_sanitizer.permit(追加したいメソッドの種類, keys: [追加したいパラメーター名])

    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/products_controller.rb
# class ProductsController < ApplicationController
class ProductsController < RankingController
  # 『search』アクション発動時、ログインしているかを確認して、リダイレクトの要否を判定。
  before_action :authenticate_user!, only: :search

  def index
    # @products = Product.all
    # 最新順に並び替えの為（新規作成されると、レコードが追加されるから）
    @products = Product.order("id DESC").limit(20)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    # Product.create(product_params)：これだけでも『create』はできる
    # バリデーション時の表示設定のため。
    @product = Product.new(product_params)
    unless @product.save
      # インスタンス変数などが必要ない場合は『render』だけで良い。
      #『render』などを複数使用する場合、明示的に終わりを宣言することが必要（return）
      render :new
    end
  end

  def search
    #『like句』をwhereメソッドと共に使用。
    #『（カラム名: バリュー）と記述して、レコードを取得』『where(user_id: @user.id)』

    #下記の場合
    # 前者："検索するカラム名 LIKE(?)"（書き方固定）
    # 後者："検索するキーワード"
    #      params内（URLで送られてくる）のkey『keyword』に対応するバリューに
    #      曖昧文字列（%）を付ける＝『〜バリュー〜』（値）
    @products = Product.where("title LIKE(?)", "%#{params[:keyword]}%").limit(20)
    # フォーマット毎の処理切り分け
    respond_to do |format|
      format.html
      format.json
    end
  end

  def search_director
    @products = Product.where("director LIKE(?)", "%#{params[:keyword_director]}%").limit(20)
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def product_params
    params.require(:product).permit(:title, :image_url, :director, :detail, :open_date)
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  layout 'mooovi'
  #『layout』で記載することで、
  #  そのコントローラでのアクションが呼ばれたあと表示するビューの
  #  レイアウトファイルを指定できる。
  #『application.html.haml』の設定を上書きし、『mooovi.html.haml』を適用可能。
  before_action :ranking
  def ranking
    # @ranking = Product.limit(5)
    # 投稿数の多い順に修正
    product_ids = Review.group(:product_id).order("count_product_id DESC").limit(5).count(:product_id).keys
    # Review.group(:product_id)：引数に指定したカラム名で、値の同じレコードをまとめる
    # .order("count_product_id DESC").limit(5)：まとまりの数が多い順に、上位５個を表示
    # .count(:product_id)：上記で、抽出したカラム名でソートがかけられるように、引数を設定
    # .keys：ハッシュのキーのみを配列で返す。
    # ->結果、まとまり数が多い順のidが取り出せる。

    # 上位５件のレコード取得
    @ranking = product_ids.map { |id| Product.find(id) }
    # @ranking = Product.find(product_ids) / = Product.where(id: product_ids)では
    # レコードがid順になってしまう為、mapメソッド を用いて順番に取り出し、処理を施したのちに格納させる。
  end
end

app/controllers/reviews_controller.rb
# class ReviewsController < ApplicationController
class ReviewsController < RankingController
  # 『new』アクション発動時、ログインしているかを確認して、リダイレクトの要否を判定。
  before_action :authenticate_user!, only: :new

  def new
    @review = Review.new
    @product = Product.find(params[:product_id])
    # ↑URL内に記載されているkey名で渡される為
    #『/products/:product_id/reviews/new(.:format)』
  end

  def create
    # 下記の記述で１行。（パラメータで送られてくるものをモデルインスタンスとして生成＆保存）
    Review.create(review_params)
      # 下記の２行記述は生成、そして保存の流れ。
      # パラメータでインスタンス変数を生成。その後、それを保存。
      # @review = Review.new(review_params)
      # @review.save
    redirect_to controller: "products", action: "index"
      # リダイレクトの方法は、下記でも可能。
      # redirect_to controller: :products, action: :index

  end

  private
  def review_params
    # アソシエーション&foreign_keyを設定していても、『merge』メソッドは必要！
      # params.require(:review).permit(:rate, :review).merge(product_id: params[:product_id])
    # reviewsテーブルにuser_idカラム追加後
    params.require(:review).permit(:rate, :review).merge(product_id: params[:product_id], user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_posted_time(time)
    time.in_time_zone("Tokyo") #タイムゾーン変換
    @time = time.in_time_zone("Tokyo").strftime("%Y-%m-%d %H:%M:%S") #不要な表示削除
  end

end

app/views/layouts/application.html.haml
!!!
%html.pc{:lang => "ja", "xmlns:fb" => "http://ogp.me/ns/fb#", "xmlns:og" => "http://ogp.me/ns#"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %title Mooovi0
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,700,500' rel='stylesheet", :rel => "stylesheet", :type => "text/css"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.yj950-2
    #wrapper
      #yjContentsHeader
        %nav.globalnav
          .globalnav__menu
            %ul.gmenu
              %li.logo{style: "float:left"}
                %a{href: "/"} mooovi0
      -# deviseでフラッシュメッセージを出す設定
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert
      = yield

app/views/layouts/mooovi.html.haml
!!!
%html.pc{:lang => "ja", "xmlns:fb" => "http://ogp.me/ns/fb#", "xmlns:og" => "http://ogp.me/ns#"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %title mooovi0
    %link{:href => "http://fonts.googleapis.com/css?family=Signika:700,300,400,600", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body.yj950-2
    #wrapper
      #yjContentsHeader
        %nav.globalnav
          .globalnav__menu
            %ul.gmenu
              %li.logo{style: "float: left"}
                %a{href: "/"} mooovi0
              - if user_signed_in?
                %li.entry_button{style: "float: right"}
                  = link_to 'サインアウト', "/users/sign_out", method: :delete
                %li.entry_button{style: "float: right"}
                  = link_to 'マイページ', "/users/#{current_user.id}"
                %li.entry_button{style: "float: right"}
                  %a{href: "/products/search_director"} 監督名で投稿
                %li.entry_button{style: "float: right"}
                  %a{href: "/products/search"} 作品名で投稿

              - else
                %li.entry_button{style: "float: right"}
                  = link_to "サインイン", "/users/sign_in"
                %li.entry_button{style: "float: right"}
                  %a{href: "/products/search"} 投稿する
            -#
              %li.entry_button{style: "float: right"}
                %a{href: "/products/search"} 投稿する
      -# deviseでフラッシュメッセージを出す設定を追記
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert
      #contents.bgcolor-white.pt1em.pb1em
        #main_cnt_wrapper
          #yjContentsBody
            .yjContainer
              = yield
              #yjSub
                %aside.section
                  %h4.text-small.hr-bottom--thin.no-space-bottom
                    %i.icon-crown.color-gray-light
                    投稿ランキング
                  %ul.listview.listview--condensed.text-small
                    - @ranking.each.with_index(1) do |product, i|
                      -# 『each』メソッド と『with_index』メソッド を使用
                      -# 引数を渡すことで、その番号からナンバリングが開始される。
                      %li{"data-cinema-id" => "346394"}
                        %a{href: "/products/#{product.id}"}
                          .box
                            .box__cell.w40.align-center
                              %p.label.bgcolor-gray-lighter.align-center
                                = i
                            .box__cell.pl1em
                              %p.text-xsmall.no-space
                                = product.title
                              - if product.image_url?
                                %img{src: "#{product.image_url}", alt: "#{product.title}", style: "height: 283px; width: 200px;"}
                              - else
                                = image_tag("noimage.png", alt: "#{product.title}", style: "height: 283px; width: 200px;")
    .copyright
      Copyright 2018  xoxo Corporation.

app/views/products/_search.html.haml
%article.section
  .container
    %header.header.header--section
      %h2.text-middle
        %i.icon-movie.color-gray-light
        検索結果
    %ul.listview.js-lazy-load-images
      - if @products.present?
        - @products.each do |product|
          %li
            %a.listview__element--right-icon{href: "/products/#{product.id}/reviews/new", title: "#{product.title}"}
              .position-right.p1em
                %i.icon-chevron-right.color-sub
              .row.no-space-bottom
                .col2
                  .thumbnail.thumbnail--movies
                    .thumbnail__figure{style: "background-image:url(#{product.image_url});", title: "#{product.title}"}
                .col6.push6
                  %h3.text-middle.text-break
                    %span.color-sub
                      = product.title
                    %p.text-xsmall.text-overflow
                      = product.detail
                      %br
                      %br
                      -# 『application_controller.rb』での記述呼び出し
                      - if @path.is('#search_director')
                        監督名：#{product.director}

      - else
        一致する作品はありませんでした。
        %br
        %br
        レビューを投稿したい作品を登録してみよう！
        %br
        = link_to "作品を登録", new_product_path

app/views/products/create.html.haml
#yjMain
  %article.section
    .container
      %header.header.header--section
        %h2.text-middle
          %i.icon-movie.color-gray-light
          作成完了
      = link_to "『投稿』", search_products_path
      ページから、
      %br
      作品を検索してレビューを投稿してみよう！

app/views/products/index.html.haml
%span.yjGuid
  %a#yjContentsStart{name: "yjcontentsStart"}
  %img{alt: "ここから本文です", height: "1", src: "http://i.yimg.jp/yui/jp/tmpl/1.1.0/audionav.gif", width: "1"}
#yjMain
  %article.section
    .container
      %header.header.header--section
        %h2.text-middle
          %i.icon-movie.color-gray-light
          新着作品
      %ul.thumbnails.thumbnail--movies.row.grid4.js-lazy-load-images.js-my-check-stats#list-module
        - @products.each do |product|
          %li.col
            %a{href: "/products/#{product.id}"}
              - if product.image_url.present?
                .thumbnail__figure{style: "background-image:url(#{product.image_url});"}
              - else
                .thumbnail__figure{style: "background-image:url(https://lh3.googleusercontent.com/gi4lCkMdhnV6Ni4FkFaYXpDZ7Nwmy7aul6zhDevbmAfKldJ08nRa0DqIxJtx1bGQmzEpvGcEJTyEB2AbAWT283Asdzivpy6Q-3iL2-I5EL7Ha1jD_pa-oWeybZif92xUcUP4romy3gFeSK42-yTvbyKhx_5gK2qkX8fm3yxcrT0Lv17hO1lRQDRRzWVuGzrDb4Au4Qml1qJFRClYmo3D6hez5jc9Qyq0qj_7E9FrCH96Ji_LM7DGRfOJk4Mkn-ffi4JpXm6cN9CTiCIeEwOsesUPULcDxSGPqrDbxn_ds3AaCmM6TP-RWFWwm57BPxDzFqbzSTJmFnWNLqUgxvfx0ejbQbiNmqiyBrXXI68qbUxBXg2d84xILQDHND46_8zdpkSrhUj7Fnnty_uzcmp5AnRgAvSU4IDgxMWhW0lUhWiAQvGMpqVg56Z4yylGZprlS0KT3B1t8Z4gqVwmyqKuWnLw-osMkpWISxhWjAsm-t8p7U7e7V4VSBi5NFA2QJillPt3OrKV6H_s6RoanlZvdJLzmOLw_LtXrvjccasOCQvOV0L0mM8bFbey-b_j8MCKHq5SJ1aXut6PqI_ieWX_VAjaykHFs9UUPDOdhdUW3NsnWeWy0pXJbN8Pzwzc7RK0AD_nyyyjDaYaYvTcgi0QT74DamYVxF-u=w320-h453-no);"}
            .thumbnail__caption
              %h3.text-xsmall.text-overflow{title: "タイトル"} #{product.title}
              %p.text-small
                %span.rating-star
                  -if product.reviews.average(:rate).present?
                    %i{class: "star-actived rate-#{product.review_average}0"}
                    -# ビューに長いロジックを書くと可読性が悪くなる為、
                    -# 『product.rb』にインスタンスメソッド を定義。
                  -else
                    %i{class: "star-actived rate-0"}

app/views/products/new.html.haml
%span.yjGuid
  %a#yjContentsStart{name: "yjcontentsStart"}
  %img{alt: "ここから本文です", height: "1", src: "http://i.yimg.jp/yui/jp/tmpl/1.1.0/audionav.gif", width: "1"}
#yjMain
  %article.section
    .container
      %header.header.header--section
        %h2.text-middle
          %i.icon-movie.color-gray-light
          投稿
      %div
        -# エラー（バリデート）時のメッセージ追加
        - @product.errors.full_messages.each do |product|
          %p.input_error
            %em
              ※#{product}
            %br
        -# 入力フォーム
        = form_for @product do |f|
          %div{style: "margin-top: 8px;"}
            = f.label :title, "作品タイトル", style: "margin-right: 8px;"
          %div
            = f.text_field :title, placeholder: "タイトル名入力（必須）", style: "width: 280px;"

          %div{style: "margin-top: 8px;"}
            = f.label :image_url, "作品イメージ", style: "margin-right: 8px;"
          %div
            = f.text_field :image_url, placeholder: "作品のパッケージ画像のリンク入力", style: "width: 280px;"

          %div{style: "margin-top: 8px;"}
            = f.label :director, "監督", style: "margin-right: 8px;"
          %div
            = f.text_field :director, placeholder: "監督名入力（必須）", style: "width: 280px;"

          %div{style: "margin-top: 8px;"}
            = f.label :open_date, "公開日時", style: "margin-right: 8px;"
          %div
            = f.text_field :open_date, placeholder: "（例）2016年2月28日", style: "width: 280px;"

          %div{style: "margin-top: 8px;"}
            = f.label :detail, "あらすじ", style: "margin-right: 8px;"
          %div{style: "margin-bottom: 8px;"}
            = f.text_area :detail, placeholder: "あらすじ入力", style: "width: 100%; height: 300px;"
          .row
            .col10.push1
              = button_tag type: "submit", class: "btn btn--block" do
                投稿する
                %i.icon-arrow-right

              -#
                = f.submit "投稿する", class: "btn btn--block"
                %i.icon-arrow-right
                『投稿する→』を実現するために、『=button_tag』で書き直し

app/views/products/search.html.haml
%span.yjGuid
  %a#yjContentsStart{name: "yjcontentsStart"}
  %img{alt: "ここから本文です", height: "1", src: "http://i.yimg.jp/yui/jp/tmpl/1.1.0/audionav.gif", width: "1"}
#yjMain
  %article.section
    .container
      %header.header.header--section
        %h2.text-middle
          %i.icon-movie.color-gray-light
          投稿する作品を検索
      = form_tag("/products/search", method: :get) do
        %input.search__query#search_products{name: "keyword", placeholder: "作品名で検索"}
          %button.btn-search{title: "検索", type: "submit"}
            %i.icon-search
      -# <form accept-charset="utf-8" action="/" class="js-search-submit" method="get">
  = render "search"

app/views/products/search_director.haml
%span.yjGuid
  %a#yjContentsStart{name: "yjcontentsStart"}
  %img{alt: "ここから本文です", height: "1", src: "http://i.yimg.jp/yui/jp/tmpl/1.1.0/audionav.gif", width: "1"}
#yjMain
  %article.section
    .container
      %header.header.header--section
        %h2.text-middle
          %i.icon-movie.color-gray-light
          投稿する作品を検索
      = form_tag("/products/search_director", method: :get) do
        %input.search__query#search_directors{name: "keyword_director", placeholder: "監督者で検索"}
          %button.btn-search{title: "検索", type: "submit"}
            %i.icon-search

  = render "search"

app/views/products/show.html.haml
%span.yjGuid
  %a#yjContentsStart{name: "yjcontentsStart"}
  %img{alt: "ここから本文です", height: "1", src: "http://i.yimg.jp/yui/jp/tmpl/1.1.0/audionav.gif", width: "1"}
#yjMain
  %article.section
    .container
      %header.header.header--section
        %h2.text-middle
          %i.icon-movie.color-gray-light
          = @product.title
      %p{style: "float: left;"}
        / %p{style: "text-align: center;"}
        - if @product.image_url?
          %img{src: "#{@product.image_url}", alt: "#{@product.title}", style: "height: 283px; width: 200px; padding-right: 10px;"}
        - else
          = image_tag("noimage.png", alt: "#{@product.title}", style: "height: 283px; width: 200px; padding-right: 10px;")
        %p
          監督
        %p
          = @product.director
        %p
          公開日時
        %p
          = @product.open_date
        %p
          あらすじ
        %p
          = @product.detail
        %div{style: "display: block; content: ""; clear: both;"}

      %div{style: "text-align: right"}
        %a{href: "/products/#{@product.id}/reviews/new"} この作品を投稿する
      %header.header.header--section
        %h2.text-middle
          %i.icon-movie.color-gray-light
          みんなのレビュー
      %ul{style: "padding: 0;"}
        - @product.reviews.each do |review|
          %li{style: "border-bottom: dotted 1px;"}
            .thumbnail__caption
              %h3.text-xsmall.text-overflow{title: "#{review.user.nickname}"}
                = link_to "#{review.user.nickname}", "/users/#{review.user.id}", style: "font-size: 12px"
              %p.text-small
                %span.rating-star
                  %i{class: "star-actived rate-#{review.rate}0"}
              = simple_format(review.review)
              -# レビュー欄にて、改行を適用させる為、メソッド使用。
              %p{style: "font-size: 12px;"}
                投稿日時
                = format_posted_time(review.created_at)

app/views/reviews/new.html.haml
%span.yjGuid
  %a#yjContentsStart{name: "yjcontentsStart"}
  %img{alt: "ここから本文です", height: "1", src: "http://i.yimg.jp/yui/jp/tmpl/1.1.0/audionav.gif", width: "1"}
#yjMain
  %article.section
    .container
      %header.header.header--section
        %h2.text-middle
          %i.icon-movie.color-gray-light
          投稿
      %div
        %ul.listview.js-lazy-load-images
          %li{style: "margin-bottom: 15px;"}
            %a.listview__element--right-icon{href: "/products/#{@product.id}"}
              .box
                .box__cell.w80
                  .thumbnail.thumbnail--photo
                    - if @product.image_url.present?
                      .thumbnail__figure{style: "background-image: url(#{@product.image_url});"}
                    - else
                      .thumbnail__figure{style: "background-image: url(https://lh3.googleusercontent.com/gi4lCkMdhnV6Ni4FkFaYXpDZ7Nwmy7aul6zhDevbmAfKldJ08nRa0DqIxJtx1bGQmzEpvGcEJTyEB2AbAWT283Asdzivpy6Q-3iL2-I5EL7Ha1jD_pa-oWeybZif92xUcUP4romy3gFeSK42-yTvbyKhx_5gK2qkX8fm3yxcrT0Lv17hO1lRQDRRzWVuGzrDb4Au4Qml1qJFRClYmo3D6hez5jc9Qyq0qj_7E9FrCH96Ji_LM7DGRfOJk4Mkn-ffi4JpXm6cN9CTiCIeEwOsesUPULcDxSGPqrDbxn_ds3AaCmM6TP-RWFWwm57BPxDzFqbzSTJmFnWNLqUgxvfx0ejbQbiNmqiyBrXXI68qbUxBXg2d84xILQDHND46_8zdpkSrhUj7Fnnty_uzcmp5AnRgAvSU4IDgxMWhW0lUhWiAQvGMpqVg56Z4yylGZprlS0KT3B1t8Z4gqVwmyqKuWnLw-osMkpWISxhWjAsm-t8p7U7e7V4VSBi5NFA2QJillPt3OrKV6H_s6RoanlZvdJLzmOLw_LtXrvjccasOCQvOV0L0mM8bFbey-b_j8MCKHq5SJ1aXut6PqI_ieWX_VAjaykHFs9UUPDOdhdUW3NsnWeWy0pXJbN8Pzwzc7RK0AD_nyyyjDaYaYvTcgi0QT74DamYVxF-u=w320-h453-no);"}
                .box__cell.pl1em
                  %h3.text-middle.text-break.color-sub
                    =@product.title
                  %p.text-small
                  %p.text-small.opacity-60
      = form_for [@product, @review] do |f|
        .div{style: "margin: 8px 0;"}
          = f.label :rate, "点数", style: "margin-right: 8px;"
          = f.number_field :rate, value: "1", max: "10", min: "1", class: "search__query", style: "text-align: right; padding-right: 1em;"
          (10段階評価)
          -# この位置に記載することで、『div』の中に入れられる。
        .div{style: "margin: 8px 0;"}
          = f.label :review, "レビュー欄", style: "margin-right: 8px;"
          = f.text_area :review, placeholder: "レビューを書いてね！", style: "width: 100%; height: 300px;"
        .row
          .col10.push1
            = button_tag type: "submit", class: "btn btn--block" do
              投稿する
              %i.icon-arrow-right